#!/usr/bin/env ansible-playbook -i inventory

---

- name: simple provisioner
  hosts: all
  sudo: yes
  gather_facts: false
  connection: local
  tasks:
    - shell: apt-get upgrade -y; apt-get update
    #- shell: apt-get install linux-image-extra-$(uname -r) -y
    #- shell: apt-get install -linux-image-extra-virtual -y
    #- shell: apt-get install python python-apt -y
